### ISSUE TITLE
Documentation site seems to incorrectly link to getmintleaf.org

### ISSUE THREAD

**Issue by icnocop** [qamatic/testcontrol.net#3]
Hi.

Thank you for testcontrol.net.

I noticed that [https://qamatic.github.io/testcontrol.net](https://qamatic.github.io/testcontrol.net) seems to incorrectly link to [http://getmintleaf.org/](http://getmintleaf.org/) in the left pane/sidebar.

![testcontrol](https://user-images.githubusercontent.com/507649/39154243-69660638-4702-11e8-86a9-d03fa985ab64.png)

Thank you.

**Comment by qamatic** [comment]
Thanks for notifying us.  The dead link got removed for now.
